### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by kiwi0fruit** [StefanPeev/Linguistics-Pro#2]
I've looked through Linguistics Pro/Lingua Franca fonts licenses and there is one thing that bothers me:

```
Copyright (c) 2003-2004 the GUTenberg project for the Greek glyphs, which are
licensed under the Latex Public Project License (LPPL).
```

I'm not sure that it's possible to mix LPPL with OFL. I'm not certain but at first they look incompatible. Are sure that it's OK to add Greek letters from GUTenberg project for the Greek glyphs?

(Other parts of the license seem to be OK and compatible. In case LPPL is not compatible with OFL the font can be split into two parts: Greek part and all other. It can be easily used with css fallback of ucharclasses *TeX package - if splitting by it's Unicode ranges).

**Comment by StefanPeev** [comment]
I'll check this point! Thanks for the comment!

**Comment by kiwi0fruit** [comment]
I've got response from Andreas Nolda on this issue:

As far as I can see,
LPPL § 10 (1) - with reference to § 6 - allows for adding the Greek
glyphs into the Lingua Franca font:

 * § 6(1) is not relevant here, since Lingua Franca is no direct
   replacement for a math font.
 * § 6(2) is respected, given the ChangeLog and the COPYING files of
   the Lingua Franca distribution.
 * § 6(3) is respected, too.
 * § 6(4.2) holds in principle, although I could add an explicit URL
   referring to the Fourier package on CTAN.

https://www.latex-project.org/lppl/lppl-1-3/

**Comment by kiwi0fruit** [comment]
But this still leaves the need to check out Greek letters font license... as it may differ from Fourier Gutenberg package license...

**Comment by kiwi0fruit** [comment]
From https://ctan.org/texarchive/fonts/fourier-GUT
```
2 LICENCE
The licence of fourier-GUTenberg is lppl (latex public
project licence). All the files of this distribution remain in directories 
wich name is "fourier".
texmf/dvips/fourier
texmf/fonts/tfm/public/fourier
texmf/fonts/type1/public/fourier
texmf/fonts/vf/public/fourier
texmf/tex/latex/fourier
```
Seems like it's LPPL.

So Linguistics Pro/Lingua Franca license seems to be OK. But still it had a rather complex history so only a lawyer can tell for sure...

**Comment by kiwi0fruit** [comment]
I've read more about sublicening https://softwareengineering.stackexchange.com/questions/189633/what-sublicense-actually-means

And it seems to me that in order to be able relicense Utopia under OFL we should make sure that rights that we grant and restrict in OFL are given to us by Utopia license.

**Comment by StefanPeev** [comment]
And what about Heuristica made by Andrey V. Panov? It's under OFL. Actually Lingua Franka (Utopia Nova) is a derivative work of Heurististica.

**Comment by kiwi0fruit** [comment]
It's all the same problem actually - is it OK to relicense Utopia under OFL (Heuristica was derived from Utopia)? Andrey Panov did it. But it's not obvious if it's OK - it needs checking.

**Comment by StefanPeev** [comment]
"There was controversy around the license regarding the status of the font files as free software. Many distributors (with one of the prominent being the Debian project), to prevent being sued, opted to state clearly that the fonts had a non-clear license which prevented it from being freely redistributable with modifications. After considerable debate, Adobe formally donated the Type 1 version of the font, on October 11, 2006, to the TeX Users Group (TUG), with clarified concerns regarding its use licensing, so that it could be used with, for instance, Donald Knuth's program TeX, a digital typesetting system for computers. The version donated consisted of the Roman (Regular), Italic, Bold, and Bold Italic versions of the typeface, differently from the commercial version offered as part of the Adobe Originals Pack. On **November 17, 2006**, Karl Berry, the TeX Users Group President, gave **irrevocable permissions of the font to any third party and it constitutes free software**." (Wikipedia)

**Comment by kiwi0fruit** [comment]
Yep, because of that this question can be asked - and I'm expecting that the answer is "yes we can sublicense under OFL". But this needs checking because of this: https://github.com/StefanPeev/Linguistics-Pro/issues/2#issuecomment-374831964

**Comment by StefanPeev** [comment]
Copyright 2006 Han The Thanh - Vntopia
Copyright (c) 2008-2012, Andrey V. Panov - Heuristica
It's all after Karl Berry's permissions.

Linguistics Pro doesn't change the licensing. It's already OFL.

**Comment by kiwi0fruit** [comment]
There is another thing that bothers me: here is a post from http://ospublish.constantvzw.org/blog/typo/the-status-of-utopia backup: https://web.archive.org/web/20170119052008/http://ospublish.constantvzw.org/blog/typo/the-status-of-utopia

Thomas Phinney

Jul 7, 2008 at 1:41 am

Further to this, I did talk it over and discuss it with the relevant lawyer and my boss. Although we could switch those four Utopia Type 1 fonts over to OFL, it would be a big bureaucratic hassle, much like the previous licensing switch.

Given how open the current licensing is, we just don’t see enough to be gained from this to make it worth the above-mentioned hassle, and are inclined to leave it alone for now.

@Fil: Of course, as a typeface designed and released around 1989, the Type 1 version of Utopia does not have extensive language support compared to our newer (e.g. Arno, Garamond Premier, Hypatia Sans) or core (e.g. Minion Pro, Myriad Pro) typefaces.

Regards,

T
----
end of quote.

If it's that easy to sublicense Utopia as OFL why he didn't mention it? Why Adobe lawyer didn't tell him about this possibility? (the guy seems to be from Adobe).

UPD: continuation of the story: https://web.archive.org/web/20170119050751/http://ospublish.constantvzw.org/blog/typo/an-update-on-the-status-of-utopia

**Comment by kiwi0fruit** [comment]
And about Vtopia and Heuristica copyright and licenses you better see latest version of Lingua Franca https://fontlibrary.org/th/font/lingua-franca

It looks like the license and copyright notices were improved and bugfixed since the time you forked.

**Comment by StefanPeev** [comment]
Thank you! I really appreciate your efforts!
I'm in a strange position now. I started from a font with OFL (Utopia Nova), which no longer exists. So I need to proove again that I started from a OFL font.

**Comment by kiwi0fruit** [comment]
There is yet another option: ask **all** copyright holders that listed in the License to relicense the font under original Utopia license. So that there would be no need to do questionable switch from Utopia license to OFL.

**Comment by kiwi0fruit** [comment]
And the last option is to relax and wait for [Source Serif Pro](https://github.com/adobe-fonts/source-serif-pro) to get [promised](https://blog.typekit.com/2018/08/16/source-serif-italics/) Cyrillic and Greek italic:

> The Italics have Adobe Latin-3 support today, just like the first release of the Roman did. Naturally, the plan is to align the character support across all styles, so that there are Greek and Cyrillic italics as well as AL-4 support for it. With Google’s support, we’ve been able to enlist the help of Irene Vlachou and Emilios Theofanous to help draw the Greek Italic.

**Comment by nolda** [comment]
>  although I could add an explicit URL referring to the Fourier package on CTAN.

Done in latest release 1.20 of the Lingua Franca fonts (available directly from [my homepage](https://andreas.nolda.org/software.html#lingua-franca), since FontLibrary is currently down). The release contains clarified copyright notices and, for convenience, a folder with licenses of ancestor fonts.
