### ISSUE TITLE
numeric features

### ISSUE THREAD

**Issue by rdtennent** [StefanPeev/Linguistics-Pro#4]
LinguisticsPro-Regular.otf has just onum whereas the Italic, Bold and BoldItalic variants have onum, pnum and tnum.

**Comment by StefanPeev** [comment]
Thank you for the notice. I prepare a completely new version of Linguistics Pro and this issue will be solved in the new version.

**Comment by StefanPeev** [comment]
Solved!

**Comment by kenmcd** [comment]
`pnum` does not work in Regular from this repo.

I this source repo just a fake to link to your pay site?
Are the fonts and sources there actually up-to-date?

**Comment by StefanPeev** [comment]
@kenmcd An update of all styles to version 1.075 is currently being prepared. The old files are still on the localfonts.eu site. The new ones will be both there and in the GitHub repository. The update will be completed by the end of September at the latest.
