### ISSUE TITLE
em dash is too short

### ISSUE THREAD

**Issue by intractabilis** [StefanPeev/Linguistics-Pro#5]
Em dash symbol at Unicode code point 2014 is shorter than it is supposed to be. Moreover, it's different in the bold and regular typefaces: the bold typeface has the correct length of bold M.

Here is a demonstration with a MWE and comparison with another Utopia derivative:
```LaTeX
\documentclass[12pt]{scrbook}

\usepackage{fontspec}

\setmainfont{Linguistics Pro}
\newfontfamily\heuristica{Heuristica}

\begin{document}

\halign{\hfil # & # \hfil \cr
Linguistics Pro: & the sounds of English\char"2014are represented \cr
Linguistics Pro: & the sounds of EnglishMare represented \cr
{\heuristica Heuristica:} & {\heuristica the sounds of English\char"2014are represented}\cr
Linguistics Pro Bold: & \textbf{the sounds of English\char"2014are represented} \cr}

\end{document}
```

Result:

![изображение](https://user-images.githubusercontent.com/45959195/111897540-ab523000-89dd-11eb-9feb-6421857ec494.png)

**Comment by intractabilis** [comment]
I suggest the following workaround for LuaLaTeX until this bug is fixed:

```LaTex
\newfontfamily\heuristica{Heuristica}

\begin{luacode}
    function subsemdash(head,  groupcode, size, packtype, direction, attributelist)
        for n, st in node.traverse_id(29, head) do
            if 0x2014 == n.char and "LinguisticsPro-Regular" == font.fonts[n.font].fullname then
                local hfontname = string.gsub(font.fonts[n.font].name, "LinguisticsPro", "Heuristica")
                hfontname = string.gsub(hfontname, "+tlig;", "")
                for i, f in font.each() do
                    if f.name == hfontname then
                        n.font = i
                        break
                    end
                end
            end
        end
        return true
    end
\end{luacode}

\AtBeginDocument{
    \luaexec{
        luatexbase.add_to_callback("hpack_filter", subsemdash, "Substitute emdash")
    }
}
```

This code substitutes `LinguisticsPro`'s em dash with `Heuristica`'s. The result for the topic's MWE:

![изображение](https://user-images.githubusercontent.com/45959195/111901926-06911c00-89f8-11eb-8937-c6174b50272c.png)

**Comment by StefanPeev** [comment]
@intractabilis Thank you for your report! Linguistics Pro is on updating and I'll take in consideration the em dash case.

**Comment by StefanPeev** [comment]
@intractabilis The problem is solved in v.1.080. Please, check the result and comment.
